nt_arity(wypowiedzenie, 0).
nt_arity(agl, 3).
nt_arity(agl1, 2).
nt_arity(condaglt,2).
nt_arity(ff, 12).
nt_arity(ff1, 12).
nt_arity(fl, 7).
nt_arity(fl1, 7).
nt_arity(flno, 7).
nt_arity(fno, 8).
nt_arity(fno1, 8).
nt_arity(formaczas, 8).
nt_arity(formaczas1, 9).
nt_arity(formaprzym, 3).
nt_arity(formaprzysl, 1).
nt_arity(formarzecz, 2).
nt_arity(fpm, 6).
nt_arity(fps, 6).
nt_arity(fpt, 8).
nt_arity(fw, 9).
nt_arity(fw1, 9).
nt_arity(fwe, 11).
nt_arity(fzd, 8).
nt_arity(fzde, 6).
nt_arity(fzdj, 9).
nt_arity(fzdkor, 8).
nt_arity(fzdsz, 8).
nt_arity(knoatr, 8).
nt_arity(knodop, 8).
nt_arity(knoink, 8).
nt_arity(knom, 7).
nt_arity(knopm, 8).
nt_arity(kor, 2).
nt_arity(kor1, 1).
nt_arity(kprzym, 7).
nt_arity(kprzysl, 5).
nt_arity(kpsink, 6).
nt_arity(kpspm, 6).
nt_arity(kpsps, 6).
nt_arity(kptink, 8).
nt_arity(kptno, 8).
nt_arity(kptpm, 8).
nt_arity(kptps, 8).
nt_arity(kweink, 10).
nt_arity(kweneg, 11).
nt_arity(kwer, 9).
nt_arity(kwer1, 9).
nt_arity(morfagl, 3).
nt_arity(partykula, 1).
nt_arity(przec, 0).
nt_arity(przecsp, 0).
nt_arity(przyimek, 2).
nt_arity(pyt, 2).
nt_arity(spoj, 3).
nt_arity(spoj1, 2).
nt_arity(spojnik, 1).
nt_arity(zaimneg, 5).
nt_arity(zaimno, 5).
nt_arity(zaimos, 3).
nt_arity(zaimprzym, 3).
nt_arity(zaimprzys, 1).
nt_arity(zaimpyt, 5).
nt_arity(zaimrzecz, 3).
nt_arity(zaimwzg, 5).
nt_arity(ze, 12).
nt_arity(zj, 11).
nt_arity(znakkonca, 1).
nt_arity(zp, 10).
nt_arity(zr, 10).
nt_arity(zsz, 10).

%%% Local Variables: 
%%% coding: utf-8
%%% mode: prolog
%%% End: 
